/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:637e7401-576b-4487-9859-e4298a0f22f2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_lscmtrhzK",
    "aws_user_pools_web_client_id": "58gnv6q94sgf47rtutaqbf1q4l",
    "oauth": {
        "domain": "ml52sj15xmud-staging.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://master.d137sqorxi6sri.amplifyapp.com/",
        "redirectSignOut": "https://master.d137sqorxi6sri.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://iwatukwgybdg5pizabdthswbcu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jmxhjoxbb5hwdfpp6tysjrdnzi"
};


export default awsmobile;
